server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ebrainsoft_study?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ebsoft
    password: ebsoft

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ebsoft.ebstudytemplates3week
  configuration:
    arg-name-based-constructor-auto-mapping: true
